/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.language.fsql


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FSQLRuntimeModule extends AbstractFSQLRuntimeModule {
}
