/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.language.fsql


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FSQLStandaloneSetup extends FSQLStandaloneSetupGenerated {

	def static void doSetup() {
		new FSQLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
